In [1]:
# Import 
import os, sys
import numpy as np 
import pandas as pd
PLAYID = 2020110810-1708
DATANAME = "tracking2020.csv"

In [31]:
# Process the play specified
tracking = pd.read_csv(os.path.join("data", DATANAME))
tracking = tracking.astype({"gameId" : str, "playId" : str})
tracking["uniqueId"] = tracking.gameId + "-" + tracking.playId

In [32]:
# Only keep desired columns
tracking_columns_to_keep = ['x', 'y', 'event', 'displayName', 'position', 'frameId', 'playDirection', 'uniqueId']
tracking = tracking[tracking_columns_to_keep]

In [72]:
print(tracking.event.unique())
tracking.event.value_counts()

['None' 'kickoff' 'touchback' 'ball_snap' 'field_goal_attempt'
 'field_goal' 'kick_received' 'first_contact' 'tackle' 'punt' 'punt_land'
 'punt_downed' 'out_of_bounds' 'extra_point_attempt' 'extra_point'
 'fair_catch' 'punt_received' 'touchdown' 'kickoff_land' 'punt_muffed'
 'fumble_offense_recovered' 'autoevent_kickoff' 'onside_kick'
 'kick_recovered' 'extra_point_missed' 'punt_play' 'line_set' 'fumble'
 'fumble_defense_recovered' 'free_kick' 'field_goal_missed'
 'field_goal_blocked' 'pass_forward' 'pass_arrived' 'pass_outcome_caught'
 'lateral' 'run' 'pass_shovel' 'field_goal_play' 'extra_point_blocked'
 'penalty_flag' 'man_in_motion' 'punt_fake' 'punt_blocked' 'drop_kick'
 'field_goal_fake' 'pass_outcome_incomplete' 'safety' 'snap_direct'
 'handoff' 'kickoff_play' 'qb_sack' 'shift' 'huddle_break_offense'
 'huddle_start_offense' 'two_point_conversion' 'field_goal_miseed']

None                        11289481
ball_snap                      88067
kickoff                        60214
punt                           40848
touchback                      39836
autoevent_kickoff              36041
tackle                         34983
first_contact                  34822
extra_point_attempt            27186
kick_received                  26105
extra_point                    24909
field_goal_attempt             19711
punt_received                  16813
field_goal                     16629
fair_catch                     11730
punt_land                      10557
out_of_bounds                   9959
kickoff_land                    8809
punt_downed                     5290
line_set                        3634
field_goal_missed               2875
extra_point_missed              1633
fumble                          1472
onside_kick                     1472
fumble_offense_recovered        1403
fumble_defense_recovered        1334
punt_muffed                      782
kick_recovered                   598
touchdown                        506
free_kick                        460
punt_fake                        345
field_goal_blocked               299
pass_forward                     253
run                              253
punt_play                        230
extra_point_blocked              230
punt_blocked                     207
lateral                          184
pass_arrived                     184
penalty_flag                     184
pass_outcome_caught              161
snap_direct                      138
drop_kick                        138
safety                           115
pass_outcome_incomplete          115
kickoff_play                     115
man_in_motion                     69
handoff                           46
field_goal_play                   46
huddle_start_offense              46
pass_shovel                       46
shift                             23
field_goal_miseed                 23
huddle_break_offense              23
two_point_conversion              23
field_goal_fake                   23
qb_sack                           23
Name: event, dtype: int64

In [40]:
# Read in the kickoff plays and only keep the ones needed
specific_play_ids = set((pd.read_csv('eligible_kickoff_plays.csv')).values.flatten())
tracking_ids = set(tracking.uniqueId.unique())
ids_to_keep = tracking_ids.intersection(specific_play_ids)
print(len(ids_to_keep), len(tracking_ids), len(specific_play_ids))

2663 6552 7693

In [41]:
tracking_reduced = tracking.copy()
tracking_reduced = tracking_reduced[tracking_reduced['uniqueId'].isin(ids_to_keep)]

11821701
4703684

In [90]:
football_all = tracking_reduced[tracking_reduced.displayName == 'football']
football_all[football_all.event == 'autoevent_kickoff'].uniqueId
football_all.loc[football_all.uniqueId == '2021010301-1372', :].event

80400                 None
80401                 None
80402                 None
80403                 None
80404                 None
80405                 None
80406                 None
80407                 None
80408                 None
80409    autoevent_kickoff
80410              kickoff
80411                 None
80412                 None
80413                 None
80414                 None
80415                 None
80416                 None
80417                 None
80418                 None
80419                 None
80420                 None
80421                 None
80422                 None
80423                 None
80424                 None
80425                 None
80426                 None
80427                 None
80428                 None
80429                 None
80430                 None
80431                 None
80432                 None
80433                 None
80434                 None
80435                 None
80436                 None
80437                 None
80438                 None
80439                 None
80440                 None
80441                 None
80442                 None
80443                 None
80444                 None
80445                 None
80446                 None
80447                 None
80448                 None
80449                 None
80450                 None
80451                 None
80452                 None
80453                 None
Name: event, dtype: object

In [48]:
football = tracking_reduced[(tracking_reduced.displayName == 'football') & (tracking_reduced.event == 'kickoff')]
football.head(20)

,x,y,event,displayName,position,frameId,playDirection,uniqueId
1264,74.47,26.43,kickoff,football,NaN,11,left,2021010300-40
5078,73.86,26.21,kickoff,football,NaN,11,left,2021010300-395
17454,75.05,23.85,kickoff,football,NaN,11,left,2021010300-1096
22168,75.09,23.73,kickoff,football,NaN,11,left,2021010300-1486
30149,74.92,23.73,kickoff,football,NaN,11,left,2021010300-1628
32680,44.90,26.48,kickoff,football,NaN,11,right,2021010300-1966
35031,75.08,23.67,kickoff,football,NaN,11,left,2021010300-2101
39371,74.97,23.54,kickoff,football,NaN,11,left,2021010300-2276
41993,44.97,27.15,kickoff,football,NaN,11,right,2021010300-2571
46480,74.94,23.82,kickoff,football,NaN,11,left,2021010300-2816
49146,45.22,23.79,kickoff,football,NaN,11,right,2021010300-3548
51524,45.09,23.57,kickoff,football,NaN,11,right,2021010300-3676
53468,74.31,25.79,kickoff,football,NaN,11,left,2021010300-3930
59065,44.95,23.52,kickoff,football,NaN,11,right,2021010300-4268
62716,74.69,26.91,kickoff,football,NaN,11,left,2021010301-39
68179,72.26,26.87,kickoff,football,NaN,3,left,2021010301-371
75349,47.12,26.44,kickoff,football,NaN,11,right,2021010301-852
80410,46.25,26.58,kickoff,football,NaN,11,right,2021010301-1372
83534,45.20,26.73,kickoff,football,NaN,11,right,2021010301-1986
86356,74.60,26.58,kickoff,football,NaN,11,left,2021010301-2175

In [50]:
tracking_reduced.x[tracking_reduced.playDirection == 'left'] = 120 - tracking_reduced.x[tracking_reduced.playDirection == 'left']

In [66]:
kickoff_frames = tracking_reduced.loc[(tracking_reduced.displayName == 'football') & (tracking_reduced.event == 'kickoff'), ['frameId', 'uniqueId']]
kickoff_frames = kickoff_frames.rename(columns={'frameId' : 'kickoffFrameId'})
tracking_new = pd.merge(tracking_reduced.copy(), kickoff_frames, on='uniqueId')
tracking_new = tracking_new.loc[~(tracking_new.frameId < tracking_new.kickoffFrameId), :]
tracking_new.head(20)
#for i, uniqueId in enumerate(tracking_new.uniqueId.unique()):
    #print(str(i + 1) + ':' + str(len(tracking_new.uniqueId.unique())))
    #tracking_new = tracking_new.loc[~((tracking_new.uniqueId == uniqueId) & (tracking_new.frameId < kickoff_frames['frameId'][uniqueId])), :]

,x,y,event,displayName,position,frameId,playDirection,uniqueId,kickoffFrameId
10,59.18,46.50,kickoff,Dean Marlowe,SS,11,left,2021010300-40,11
11,59.35,46.39,None,Dean Marlowe,SS,12,left,2021010300-40,11
12,59.55,46.25,None,Dean Marlowe,SS,13,left,2021010300-40,11
13,59.78,46.10,None,Dean Marlowe,SS,14,left,2021010300-40,11
14,60.04,45.92,None,Dean Marlowe,SS,15,left,2021010300-40,11
15,60.33,45.71,None,Dean Marlowe,SS,16,left,2021010300-40,11
16,60.66,45.47,None,Dean Marlowe,SS,17,left,2021010300-40,11
17,61.03,45.20,None,Dean Marlowe,SS,18,left,2021010300-40,11
18,61.44,44.92,None,Dean Marlowe,SS,19,left,2021010300-40,11
19,61.89,44.62,None,Dean Marlowe,SS,20,left,2021010300-40,11
20,62.37,44.30,None,Dean Marlowe,SS,21,left,2021010300-40,11
21,62.87,43.97,None,Dean Marlowe,SS,22,left,2021010300-40,11
22,63.40,43.63,None,Dean Marlowe,SS,23,left,2021010300-40,11
23,63.95,43.28,None,Dean Marlowe,SS,24,left,2021010300-40,11
24,64.52,42.93,None,Dean Marlowe,SS,25,left,2021010300-40,11
25,65.10,42.57,None,Dean Marlowe,SS,26,left,2021010300-40,11
26,65.70,42.21,None,Dean Marlowe,SS,27,left,2021010300-40,11
27,66.32,41.83,None,Dean Marlowe,SS,28,left,2021010300-40,11
28,66.95,41.45,None,Dean Marlowe,SS,29,left,2021010300-40,11
29,67.60,41.07,None,Dean Marlowe,SS,30,left,2021010300-40,11

In [67]:
tracking_new.event.unique()

array(['kickoff', 'None', 'touchback', 'kick_received', 'first_contact',
       'tackle', 'kickoff_land', 'out_of_bounds', 'autoevent_kickoff',
       'lateral', 'pass_outcome_caught', 'fumble',
       'fumble_defense_recovered', 'fumble_offense_recovered',
       'kick_recovered', 'free_kick', 'penalty_flag', 'touchdown',
       'kickoff_play', 'fair_catch', 'punt_received', 'onside_kick'],
      dtype=object)

In [42]:
# Open the plays information to find the result of the plays
plays = pd.read_csv(os.path.join("data", "plays.csv"))
plays = plays.astype({"playId" : str, "gameId" : str})
plays["uniqueId"] = plays.playId + "-" + plays.gameId

In [5]:
# Add the relevant information from the plays and combine the dataframes
play_columns_to_keep = ["uniqueId", "specialTeamsResult"]
combined_data = pd.merge(tracking, plays[play_columns_to_keep], on='uniqueId')

In [93]:
kickoffs = pd.read_csv(os.path.join('data', 'ProcessedKickoffs.csv'))

KeyboardInterrupt:

In [100]:
kickoffs.event.value_counts()

None                        11547932
kickoff                       172845
touchback                     107318
kick_received                  77901
tackle                         54809
first_contact                  53774
kickoff_land                   19780
autoevent_kickoff              11362
out_of_bounds                   7682
fumble                          1104
kick_recovered                   828
fumble_defense_recovered         690
fumble_offense_recovered         437
touchdown                        414
penalty_flag                     345
lateral                          253
kickoff_play                      92
punt_received                     69
pass_outcome_caught               46
onside_kick                       46
handoff                           23
free_kick                         23
punt_land                         23
shift                             23
fair_catch                        23
free_kick_play                    23
penalty_accepted                  23
punt_downed                       23
Name: event, dtype: int64

In [103]:
play_events_to_keep = ["kickoff_land", "kick_received", "touchback"]
landing_kickoffs = kickoffs[(kickoffs.event.isin(play_events_to_keep)) & (kickoffs.displayName == "football") & (kickoffs.specialTeamsResult == "Return")]

In [104]:
landing_kickoffs.head(50)

,Unnamed: 0,x,y,event,displayName,position,frameId,uniqueId,kickoffFrameId,specialTeamsResult
2155,2155,0.854833,0.003062,kick_received,football,NaN,53,2018123000-36,10,Return
5826,5826,0.853083,0.121562,kick_received,football,NaN,49,2018123000-564,11,Return
8174,8174,0.934167,0.005125,kick_received,football,NaN,53,2018123000-803,11,Return
11495,11495,0.925833,-0.028250,kick_received,football,NaN,52,2018123000-1557,11,Return
16627,16627,0.896333,-0.009688,kick_received,football,NaN,53,2018123000-2883,11,Return
18652,18652,0.877750,-0.054875,kick_received,football,NaN,51,2018123000-3397,11,Return
22795,22795,0.812833,-0.137000,kick_received,football,NaN,50,2018123001-36,11,Return
24658,24658,0.910333,-0.317188,kick_received,football,NaN,47,2018123001-356,10,Return
24692,24692,0.759333,-0.504687,out_of_bounds,football,NaN,81,2018123001-356,10,Return
26916,26916,0.917583,-0.148063,kick_received,football,NaN,47,2018123001-525,11,Return
30327,30327,0.923083,0.012437,kick_received,football,NaN,50,2018123001-2114,11,Return
32735,32735,0.853083,0.153250,kick_received,football,NaN,53,2018123001-2192,11,Return
34867,34867,0.735333,-0.244250,kickoff_land,football,NaN,34,2018123001-2597,11,Return
34878,34878,0.778333,-0.323188,kick_received,football,NaN,45,2018123001-2597,11,Return
37443,37443,0.770667,0.288812,kick_received,football,NaN,53,2018123001-2854,11,Return
40859,40859,0.909500,-0.156875,kick_received,football,NaN,51,2018123001-3591,11,Return
45331,45331,0.881333,-0.024313,kick_received,football,NaN,48,2018123002-857,11,Return
48439,48439,0.892167,-0.009688,kick_received,football,NaN,48,2018123002-1936,11,Return
50768,50768,0.855333,0.015250,kick_received,football,NaN,51,2018123002-2821,11,Return
54030,54030,0.872583,0.312250,kickoff_land,football,NaN,43,2018123002-3602,11,Return
54046,54046,0.896333,0.400938,kick_received,football,NaN,59,2018123002-3602,11,Return
64180,64180,0.947083,-0.130625,kick_received,football,NaN,52,2018123003-3288,11,Return
66414,66414,0.899750,-0.276687,kick_received,football,NaN,51,2018123004-36,11,Return
66460,66460,0.676500,-0.504500,out_of_bounds,football,NaN,97,2018123004-36,11,Return
69983,69983,0.888250,0.049937,kick_received,football,NaN,51,2018123004-741,11,Return
72802,72802,0.809750,-0.067063,kick_received,football,NaN,50,2018123004-1380,11,Return
77283,77283,0.830583,-0.070250,kick_received,football,NaN,49,2018123004-2672,11,Return
94810,94810,0.896917,0.214000,kick_received,football,NaN,51,2018123006-1345,11,Return
94865,94865,0.633583,0.521125,out_of_bounds,football,NaN,106,2018123006-1345,11,Return
97110,97110,0.723917,-0.266938,kick_received,football,NaN,46,2018123006-2312,11,Return
99328,99328,0.911667,0.180062,kick_received,football,NaN,52,2018123006-3161,11,Return
114163,114163,0.915750,-0.092000,kick_received,football,NaN,53,2018123008-36,10,Return
114231,114231,0.597500,0.539688,out_of_bounds,football,NaN,121,2018123008-36,10,Return
117854,117854,0.928000,-0.022250,kick_received,football,NaN,51,2018123008-1848,11,Return
117911,117911,0.701000,-0.542188,out_of_bounds,football,NaN,108,2018123008-1848,11,Return
122384,122384,0.879167,-0.263188,kick_received,football,NaN,54,2018123008-2566,11,Return
124494,124494,0.872417,-0.103250,kick_received,football,NaN,52,2018123008-2797,11,Return
127762,127762,0.894167,-0.062188,kick_received,football,NaN,53,2018123008-3392,11,Return
130141,130141,0.877750,-0.108875,kick_received,football,NaN,53,2018123008-3577,11,Return
130193,130193,0.691333,-0.513312,out_of_bounds,football,NaN,105,2018123008-3577,11,Return
133465,133465,0.890083,-0.305375,kick_received,football,NaN,53,2018123008-4201,11,Return
135972,135972,0.790000,-0.142625,kick_received,football,NaN,48,2018123008-4538,11,Return
138221,138221,0.884583,-0.055250,kick_received,football,NaN,53,2018123009-36,11,Return
140539,140539,0.863750,-0.175625,kick_received,football,NaN,52,2018123009-993,11,Return
142816,142816,0.762000,0.006062,kick_received,football,NaN,50,2018123009-1525,11,Return
145486,145486,0.880000,0.023125,kick_received,football,NaN,47,2018123009-1853,11,Return
147893,147893,0.906833,-0.079250,kick_received,football,NaN,49,2018123009-2598,11,Return
150262,150262,0.854167,-0.005375,kick_received,football,NaN,48,2018123009-3241,11,Return
154013,154013,0.796750,0.193938,kick_received,football,NaN,50,2018123009-3765,11,Return
156339,156339,0.939417,-0.282125,kick_received,football,NaN,51,2018123010-36,11,Return

In [105]:
landing_kickoffs[landing_kickoffs.uniqueId == "2018123001-2597"]

,Unnamed: 0,x,y,event,displayName,position,frameId,uniqueId,kickoffFrameId,specialTeamsResult
34867,34867,0.735333,-0.244250,kickoff_land,football,NaN,34,2018123001-2597,11,Return
34878,34878,0.778333,-0.323188,kick_received,football,NaN,45,2018123001-2597,11,Return

In [108]:
returned_kickoffs = kickoffs[(kickoffs.specialTeamsResult == "Return") & (kickoffs.displayName == "football")]

In [109]:
returned_kickoffs.event.unique()

array(['kickoff', 'None', 'kick_received', 'first_contact', 'tackle',
       'out_of_bounds', 'kickoff_land', 'handoff', 'fumble',
       'fumble_offense_recovered', 'fumble_defense_recovered',
       'penalty_flag', 'touchdown', 'lateral', 'kick_recovered',
       'punt_received', 'pass_outcome_caught', 'shift', 'onside_kick',
       'penalty_accepted', 'punt_downed', 'autoevent_kickoff',
       'free_kick'], dtype=object)

In [117]:
play_events_to_keep = ["kickoff_land", "kick_received", "touchback"]
good_plays = kickoffs.loc[((kickoffs.displayName == 'football') & (kickoffs.event.isin(play_events_to_keep))), ['uniqueId']]
good_kickoffs = kickoffs[kickoffs.uniqueId.isin(good_plays.uniqueId.values)]

In [121]:
kickoffs.loc[((kickoffs.displayName == 'football') & (kickoffs.event.isin(play_events_to_keep))), :]

,Unnamed: 0,x,y,event,displayName,position,frameId,uniqueId,kickoffFrameId,specialTeamsResult
2155,2155,0.854833,0.003062,kick_received,football,NaN,53,2018123000-36,10,Return
3572,3572,0.960250,0.101688,kick_received,football,NaN,54,2018123000-392,10,Touchback
3578,3578,0.963833,0.106750,touchback,football,NaN,60,2018123000-392,10,Touchback
5826,5826,0.853083,0.121562,kick_received,football,NaN,49,2018123000-564,11,Return
8174,8174,0.934167,0.005125,kick_received,football,NaN,53,2018123000-803,11,Return
...,...,...,...,...,...,...,...,...,...,...
12053883,12053883,1.006750,0.187562,touchback,football,NaN,49,2020091401-2169,11,Touchback
12054980,12054980,0.974167,0.092500,touchback,football,NaN,49,2020091401-3154,11,Touchback
12056176,12056176,0.946667,-0.098562,touchback,football,NaN,53,2020091401-3407,11,Touchback
12057846,12057846,0.623000,0.022937,kickoff_land,football,NaN,21,2020091401-4280,11,Touchback
12057908,12057908,0.978333,0.103375,touchback,football,NaN,83,2020091401-4280,11,Touchback

In [122]:
football = good_kickoffs[good_kickoffs.displayName == "football"]

In [136]:
football_recieved = football[football.event == "kick_received"]
touchback = football[football.event == "touchback"]
football_landed = football[football.event == "kickoff_land"]

In [127]:
football

2020092701-2294    1
2019121500-2968    1
2019111008-2057    1
2020121300-3368    1
2020092011-2917    1
                  ..
2019092902-2153    1
2018123008-1433    1
2019120103-2689    1
2018091602-36      1
2018093003-607     1
Name: uniqueId, Length: 4666, dtype: int64